# Generated by Django 2.1.7 on 2019-05-03 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_phone_shipping_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='status',
            field=models.CharField(choices=[('w', 'waiting for payment'), ('s', 'shiping'), ('c', 'completed')], default='w', max_length=1),
        ),
    ]
